Add basics
heintayzar-hm/Bookstore pull request #1
Opened 2022-12-08 12:40 UTC by heintayzar-hm

2022-12-08 16:25 UTC, whiz25 requested changes
Hi @heintayzar-hm, 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🎉 🎉 🎉 
- Codebase is organized 
- Most requirements have been met

## Required Changes ♻️
_Check the comments under the review._
- Add the Category component. It should only have the text "check status"

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 16:25 UTC, whiz25 commented on src/component/AddBook.jsx
> +            <input data-testid="author-title-input" type="text" placeholder="Author" value="" required />
- Please add a submit button. It should not work at this time.

2022-12-09 08:37 UTC, KayLemba approved these changes
[# STATUS: APPROVED :green_circle: :clap: 

Hello  @heintayzar-hm        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Gitflow is followed
- [x] Descriptive P.R
- [x] Descriptive README file




 

- [x] No Linter Errors







Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]

2022-12-09 08:37 UTC, KayLemba commented on src/component/AddBook.jsx
> +    return (
[OPTIONAL]It is against microverse policy to disable linters for linters help us write clean code. kindly enable eslint in this file.

2022-12-09 08:37 UTC, KayLemba commented on src/component/Book.jsx
> +class Book extends React.Component {
[OPTIONAL] Kindly enable eslint

2022-12-09 08:37 UTC, KayLemba commented on src/component/Books.jsx
> +  constructor(props) {
Kindly please enable eslint

2022-12-09 08:37 UTC, KayLemba commented on src/component/Category.jsx
> +  constructor(props) {
[OPTIONAL] Kindly Enable eslint

2022-12-09 08:37 UTC, KayLemba commented on src/component/Header.jsx
> +class Header extends React.Component {
Kindly enable eslint

2022-12-09 08:41 UTC, heintayzar-hm commented on src/component/Book.jsx
> +class Book extends React.Component {
I want to use class components. So should I update the linters folder and make a pull request for that?

2022-12-09 09:37 UTC, merged